

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - WoodPeckeriOS.framework
  - fastlane
  - target

line_length: 300

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] 